name: linter-check
on:
  - push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: MariyaArshinina/python-project-lvl1@v2      
      - name: install
        run: |
          make install
      - name: run-linter
        run: |        
          make lint
