name: linter-check
on: push
jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
      - name: chekout-code
        uses: actions/checkout@v2      
      - name: run-linter
        run: make lint
